// tslint:disable
/**
 * Vehicle Booking API by e.GO Digital 
 * Describes all backend endpoints.
 *
 * OpenAPI spec version: 2.0.5
 * Contact: hello@e-go-digital.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
